ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('auth/', include('authentication.urls'))
]

shop/urls.py
from django.urls import path
from shop.views import show_shop
from shop.views import show_shop, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, add_product_entry_ajax, create_product_flutter
from shop.views import register
from shop.views import login_user
from shop.views import logout_user
from shop.views import edit_product_entry
from shop.views import delete_product_entry

app_name = 'shop'

urlpatterns = [
    path('', show_shop, name='show_shop'),
    path('create-product-entry', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product-entry/<uuid:id>', edit_product_entry, name='edit_product_entry'),
    path('delete/<uuid:id>/', delete_product_entry, name='delete_product_entry'),
    path('create-product-entry-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

shop/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

SLIME_QUALITY_CHOICES = [
    ('Excellent', 'Excellent'),
    ('Good', 'Good'),
    ('Fair', 'Fair'),
    ('Poor', 'Poor'),
]

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()  
    description = models.TextField()
    slime_quality = models.CharField(max_length=50, choices=SLIME_QUALITY_CHOICES, default='Excellent')

    def __str__(self):
        return self.name

# name: CharField
# age: IntegerField
# is_happy: BooleanField

# class Person(models.Model):
#     name = models.CharField(max_length=80)
#     age = models.IntegerField()
#     is_happy = models.BooleanField()

# class Project(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     name = models.CharField(max_length=255)

# class Employee(models.Model):
#     department: models.Charfield(max_length=100)
#     projects: models.ManyToManyField(Project)
#     user: models.OneToOneField(User, on_delete=models.CASCADE)

shop/forms.py
from django.forms import ModelForm
from shop.models import Product
from django import forms

class ProductEntryForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "slime_quality"]
        def clean_name(self):
            name = self.cleaned_data["name"]
            return strip_tags(name)

        def clean_price(self):
            price = self.cleaned_data["price"]
            return strip_tags(price)

# class ProductEntryForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ['name', 'price', 'description', 'slime_quality']
#         widgets = {
#             'name': forms.TextInput(attrs={
#                 'class': 'w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
#             }),
#             'price': forms.NumberInput(attrs={
#                 'class': 'w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
#             }),
#             'description': forms.Textarea(attrs={
#                 'class': 'w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
#             }),
#             'slime_quality': forms.Select(attrs={
#                 'class': 'w-full p-3 border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500'
#             }),
#         }

shop/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect   # Add import redirect at this line
from shop.forms import ProductEntryForm
from shop.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import json
from django.http import JsonResponse

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = Product.objects.create(
            user=request.user,
            name=data["name"],
            price=int(data["price"]),
            description=data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@login_required(login_url='/login')
def show_shop(request):
    context = {
        'app_name': 'Online Slime Shop',
        'name': request.user.username,
        'npm': '2306171480',
        'class': 'KKI',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

def create_product_entry(request):
    form = ProductEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False) 
        product_entry.user = request.user        
        product_entry.save()                    
        return redirect('shop:show_shop')        

    context = {'form': form}
    return render(request, "create_product_entry.html", context)

def show_xml(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('shop:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
            user = form.get_user()
            if user is not None:
                login(request, user)
                response = HttpResponseRedirect(reverse("shop:show_shop"))
                response.set_cookie('last_login', str(datetime.datetime.now()))
                return response
      else:
            messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)  # Logs out the current user
    response = HttpResponseRedirect(reverse('shop:login'))  # Redirect to the login page
    response.delete_cookie('last_login')  # Optional: delete the last login cookie
    return response

def edit_product_entry(request, id):
    # Get the product entry based on the provided ID
    product_entry = Product.objects.get(pk=id)

    # Set the product entry as an instance of the form (pre-filling the form)
    form = ProductEntryForm(request.POST or None, instance=product_entry)

    # Check if the form is valid and the request method is POST (form submission)
    if form.is_valid() and request.method == "POST":
        # Save the changes to the product entry
        form.save()
        # Redirect the user to the shop page (or wherever you want)
        return HttpResponseRedirect(reverse('shop:show_shop'))

    # Pass the form with the pre-filled product data to the template
    context = {'form': form}
    return render(request, "edit_product_entry.html", context)

def delete_product_entry(request, id):
    # Get the product entry based on the provided ID
    product_entry = Product.objects.get(pk=id)

    # Delete the product entry
    product_entry.delete()

    # Redirect the user to the shop page after deletion
    return HttpResponseRedirect(reverse('shop:show_shop'))

@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    name = strip_tags(request.POST.get("name")) # strip HTML tags!
    price = strip_tags(request.POST.get("price")) # strip HTML tags!
    description = request.POST.get("description")
    user = request.user
   
    new_product = Product(
        name=name, price=price,
        description=description,
        user=user
    )
    new_product.save()

    return HttpResponse(b"CREATED", status=201)
    

shop/templates/card_info.html
<div class="bg-[#905cb6] rounded-xl overflow-hidden border-4 border-[#905cb6] p-4">
  <div class="animate-shine text-white text-center">
      <h5 class="text-lg font-semibold">{{ title }}</h5>
      <p class="text-white">{{ value }}</p>
  </div>
</div>

shop/templates/card_product.html
<div class="relative break-inside-avoid w-full md:w-2/3 lg:w-1/2 p-4">
    <!-- Decorative bars at the top -->
    <div class="absolute top-2 z-10 left-1/2 -translate-x-1/2 flex items-center -space-x-2">
      <div class="w-[3rem] h-8 bg-gray-200 rounded-md opacity-80 -rotate-90"></div>
      <div class="w-[3rem] h-8 bg-gray-200 rounded-md opacity-80 -rotate-90"></div>
    </div>
  
    <!-- Card Body -->
    <div class="relative top-5 bg-indigo-100 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-indigo-300 transform rotate-1 hover:rotate-0 transition-transform duration-300">
      <div class="bg-indigo-200 text-gray-800 p-4 rounded-t-lg border-b-2 border-indigo-300">
        <h3 class="font-bold text-xl mb-2 break-words">{{ product_entry.name }}</h3>
        <p class="text-gray-600">${{ product_entry.price }}</p>
      </div>
  
      <!-- Card Content -->
      <div class="p-4">
        <p class="font-semibold text-lg mb-2 break-words">Product Description</p>
        <p class="text-gray-700 mb-2">
          <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px),#CDC1FF_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1 break-words">{{ product_entry.description }}</span>
        </p>
  
        <!-- Slime Quality -->
        <div class="mt-4">
          <p class="text-gray-700 font-semibold mb-2">Slime Quality</p>
          <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-indigo-600 bg-indigo-200">
            {{ product_entry.slime_quality }}
          </span>
        </div>
      </div>
  
      <!-- Edit & Delete Icons -->
      <div class="absolute top-0 -right-4 flex space-x-1">
        <a href="{% url 'shop:edit_product_entry' product_entry.pk %}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
          </svg>
        </a>
        <a href="{% url 'shop:delete_product_entry' product_entry.pk %}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
        </a>
      </div>
    </div>
  </div>

shop/templates/create_product_entry.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-2xl font-bold mb-6">Add New Product</h1>

<form method="POST" class="space-y-4 max-w-lg mx-auto bg-white p-6 rounded-lg shadow-lg">
    {% csrf_token %}
    
    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div class="col-span-1">
            <label for="id_name" class="block font-medium text-gray-700">Name:</label>
            {{ form.name }}
        </div>

        <div class="col-span-1">
            <label for="id_price" class="block font-medium text-gray-700">Price:</label>
            {{ form.price }}
        </div>

        <div class="col-span-3">
            <label for="id_description" class="block font-medium text-gray-700">Description:</label>
            {{ form.description }}
        </div>
    </div>

    <div>
        <label for="id_quality" class="block font-medium text-gray-700">Slime Quality:</label>
        {{ form.slime_quality }}
    </div>

    <button type="submit" class="bg-[#905cb6] text-white py-2 px-4 rounded-md hover:bg-indigo-600 transition duration-300">
        Submit
    </button>
</form>

{% endblock content %}

shop/templates/edit_product_entry.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Page Title -->
<div class="flex justify-center mb-8">
  <h1 class="text-3xl font-bold text-gray-800">Edit Product Entry</h1>
</div>

<!-- Edit Product Form -->
<form method="POST" class="space-y-6 max-w-3xl mx-auto bg-white p-8 rounded-lg shadow-md">
    {% csrf_token %}

    <!-- Product Name -->
    <div class="mb-6">
        <label for="name" class="block text-lg font-semibold text-gray-700 mb-2">Product Name</label>
        {{ form.name }}
    </div>

    <!-- Price -->
    <div class="mb-6">
        <label for="price" class="block text-lg font-semibold text-gray-700 mb-2">Price</label>
        {{ form.price }}
    </div>

    <!-- Description -->
    <div class="mb-6">
        <label for="description" class="block text-lg font-semibold text-gray-700 mb-2">Product Description</label>
        {{ form.description }}
    </div>

    <!-- Slime Quality -->
    <div class="mb-6">
        <label for="slime_quality" class="block text-lg font-semibold text-gray-700 mb-2">Slime Quality</label>
        {{ form.slime_quality }}
    </div>

    <!-- Submit Button -->
    <div class="flex justify-end">
        <button type="submit" class="bg-[#905cb6] text-white py-3 px-6 rounded-lg font-semibold hover:bg-indigo-700 transition duration-300 ease-in-out transform hover:scale-105">
            Save Changes
        </button>
    </div>
</form>

{% endblock content %}

shop/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
<title>Slime Shop App</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<!-- shop Content Container -->
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-gray-100 flex flex-col">
  
  <!-- Card Info Section -->
  <div class="p-2 mb-6 relative">
    <div class="relative grid grid-cols-1 z-30 md:grid-cols-3 gap-8">
      <!-- Card Info with New Color and Border -->
      <div class="bg-[#905cb6] text-white rounded-xl border-4 border-[#905cb6] p-4">
        <h5 class="text-lg font-semibold text-center">NPM</h5>
        <p class="text-white text-center">{{ npm }}</p>
      </div>

      <div class="bg-[#905cb6] text-white rounded-xl border-4 border-[#905cb6] p-4">
        <h5 class="text-lg font-semibold text-center">Name</h5>
        <p class="text-white text-center">{{ name }}</p>
      </div>

      <div class="bg-[#905cb6] text-white rounded-xl border-4 border-[#905cb6] p-4">
        <h5 class="text-lg font-semibold text-center">Class</h5>
        <p class="text-white text-center">{{ class }}</p>
      </div>
    </div>
    
    <!-- Design Elements (Adjusted to match your needs) -->
    <div class="w-full px-6 absolute top-[44px] left-0 z-20 hidden md:flex">
      <div class="w-full min-h-4 bg-[#905cb6]"></div>
    </div>
    <div class="h-full w-full py-6 absolute top-0 left-0 z-20 md:hidden flex">
      <div class="h-full min-w-4 bg-[#905cb6] mx-auto"></div>
    </div>
  </div>

  <!-- Last Login Display -->
  <div class="px-3 mb-4">
    <div class="flex rounded-md items-center bg-[#905cb6] py-2 px-4 w-fit">
      <h1 class="text-white text-center">Last Login: {{ last_login }}</h1>
    </div>
  </div>

    <!-- Add New Product Entry Button -->
    <div class="flex justify-end mb-6">
      <!-- Button to open the form modal for adding a new product via AJAX -->
      <a href="{% url 'shop:create_product_entry' %}" class="bg-[#905cb6] hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105">
        Add New Product Entry
      </a>
      <button class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 ml-4" onclick="showModal();">
        Add New Product by AJAX
      </button>
    </div>

    <div id="product_entry_cards"></div>

    <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
      <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
        <!-- Modal header -->
        <div class="flex items-center justify-between p-4 border-b rounded-t">
          <h3 class="text-xl font-semibold text-gray-900">
            Add New Product Entry
          </h3>
          <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
            <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <!-- Modal body -->
        <div class="px-6 py-4 space-y-6 form-style">
          <form id="productEntryForm">
            {% csrf_token %} <!-- new addition / change -->
            <div class="mb-4">
              <label for="name" class="block text-sm font-medium text-gray-700">Product Name</label>
              <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Enter product name" required>
            </div>
            <div class="mb-4">
              <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
              <input type="number" id="price" name="price" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Enter product price" required>
            </div>
            <div class="mb-4">
              <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
              <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-indigo-700" placeholder="Enter product description" required></textarea>
            </div>
          </form>
        </div>
        <!-- Modal footer -->
        <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
          <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
          <button type="submit" id="submitProductEntry" form="productEntryForm" class="bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
        </div>
      </div>
    </div>
    
    <script>
      async function getProductEntries(){
          return fetch("{% url 'shop:show_json' %}").then((res) => res.json())
      }
    
      async function refreshProductEntries() {
        document.getElementById("product_entry_cards").innerHTML = "";
        document.getElementById("product_entry_cards").className = "";
        const ProductEntries = await getProductEntries();
        let htmlString = "";
        let classNameString = "";

        if (ProductEntries.length === 0) {
            classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
            htmlString = `
                <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                    <img src="{% static 'image/very-sad.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                    <p class="text-center text-gray-600 mt-4">No products available yet.</p>
                </div>
            `;
        } else {
            classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full";
            ProductEntries.forEach((item) => {
                const name = DOMPurify.sanitize(item.fields.name);
                const price = DOMPurify.sanitize(item.fields.price);
                const description = DOMPurify.sanitize(item.fields.description);
                const slimeQuality = DOMPurify.sanitize(item.fields.slime_quality); // Assuming this is the dropdown value

                htmlString += `
                <div class="relative break-inside-avoid">
                    <div class="absolute top-2 z-10 left-1/2 -translate-x-1/2 flex items-center -space-x-2">
                        <div class="w-[3rem] h-8 bg-gray-200 rounded-md opacity-80 -rotate-90"></div>
                        <div class="w-[3rem] h-8 bg-gray-200 rounded-md opacity-80 -rotate-90"></div>
                    </div>
                    <div class="relative top-5 bg-indigo-100 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-indigo-300 transform rotate-1 hover:rotate-0 transition-transform duration-300">
                        <div class="bg-indigo-200 text-gray-800 p-4 rounded-t-lg border-b-2 border-indigo-300">
                            <h3 class="font-bold text-xl mb-2">${name}</h3>
                            <p class="text-gray-600">${description}</p>
                            <p class="text-gray-600">Price: $${price}</p>
                        </div>
                        <div class="p-4">
                            <p class="font-semibold text-lg mb-2">Slime Quality</p>
                            <p class="text-gray-700 mb-2">${slimeQuality}</p>
                        </div>
                    </div>
                    <div class="absolute top-0 -right-4 flex space-x-1">
                        <a href="/edit-product/${item.pk}" class="bg-yellow-500 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                            </svg>
                        </a>
                        <a href="/delete/${item.pk}" class="bg-red-500 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                            </svg>
                        </a>
                    </div>
                </div>
                `;
            });
        }

        document.getElementById("product_entry_cards").className = classNameString;
        document.getElementById("product_entry_cards").innerHTML = htmlString;
      }
      refreshProductEntries();

  
      // For opening the modal
      function showModal() {
        const modal = document.getElementById('crudModal');
        modal.classList.remove('hidden');
        setTimeout(() => {
          const modalContent = document.getElementById('crudModalContent');
          modalContent.classList.remove('opacity-0');
          modalContent.classList.remove('scale-95');
        }, 50);
      }
    
      function hideModal() {
        const modal = document.getElementById('crudModal');
        const modalContent = document.getElementById('crudModalContent');
        modalContent.classList.add('opacity-0');
        modalContent.classList.add('scale-95');
        setTimeout(() => {
          modal.classList.add('hidden');
        }, 150);
      }
  
      document.getElementById('cancelButton').addEventListener('click', hideModal);
      document.getElementById('closeModalBtn').addEventListener('click', hideModal);

      function addProductEntry() {
        fetch("{% url 'shop:add_product_entry_ajax' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#productEntryForm')),
        })
        .then(response => refreshProductEntries())

        document.getElementById("productEntryForm").reset(); 
        document.querySelector("[data-modal-toggle='crudModal']").click();
  
        return false;
      }
      document.getElementById("submitProductEntry").onclick = addProductEntry
    </script>
</div>
{% endblock content %}
      <!-- }
    
      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
    
    
      window.onload = refreshProductEntries;
    </script> -->

shop/templates/newfile.html
<!-- <head>
    <title> Student Profile </title>
</head>
<body>
    <h1> My Profile </h1>
    <h3> Profile Details </h3>
    <p> hello! good morning, welcome to your student profile </p>
    <table> 
        <tr> 
            <th>Name</th>
            <th>Student ID</th>
        </tr>
        <tr>
            <td> {{ student.name }} </td>
            <td> {{ student.ID }} </td>
        </tr>
    </table>
</body> -->